---
# this playbook along with ansible.cfg, .gitignore and entire content under config
# directory serve as demo, but it still can provision a local vagrant environment
- hosts: localhost
  roles:
    - ansible
    - role: apache2
      apache_enable_moderewrite: true
    - apserv
    - role: asdf
      asdf_apps:
        # golang: 1.10.3
        # elixir: 1.7.1
        # erlang: 21.0.4
        # nodejs: 8.11.3
        packer: 1.2.5
        # postgres: 10.4
        # rebar:  3.6.0
    - curl
    - docker
    - docker-compose
    - elixir
    - erlang
    - git
    - golang
    - htop
    - mariadb
    - mc
    - nano
    - nload
    - nodejs
    - role: php
      php_extensions:
      - bcmath
      - bz2
      - cgi
      - cli
      - common
      - curl
      - dev
      - enchant
      - fpm
      # - gd # can not be installed on debian 9
      - gmp
      - imap
      - interbase
      # - intl # can not be installed on debian 9
      - json
      - ldap
      - mbstring
      - mysql
      - odbc
      - pgsql
      - phpdbg
      - pspell
      - readline
      - recode
      - soap
      - sqlite3
      - sybase
      - tidy
      - xml
      - xmlrpc
      - zip
      - xdebug
    - ssh-server
    - vim
