---
- block:
  
  - name: install plugin dependencies
    apt: name="{{ packages }}" install_recommends=no state=latest
    vars:
      packages:
        - autoconf
        - automake
        - build-essential
        - gcc
        - libncurses5-dev
        - libffi-dev
        - libgl1-mesa-dev
        - libreadline-dev
        - libssl-dev
        - libtool
        - libwxgtk3.0-dev
        - libxslt-dev
        - libyaml-dev
        - m4
        - unzip
        - unixodbc-dev

  become: true
