---
- block:

  - name: add apt signing key
    apt_key:
      id: 3361E59FF5029E6B90A9A80D09589874801DF724
      keyserver: hkp://keyserver.ubuntu.com:80
      state: present
    register: vlc_apt_key_added
    ignore_errors: yes

  - name: add apt signing key
    apt_key:
      id: 3361E59FF5029E6B90A9A80D09589874801DF724
      keyserver: keyserver.ubuntu.com
      state: present
    when: vlc_apt_key_added is failed

  - name: add ppa
    apt_repository:
      repo: "{{ item }}"
      filename: vlc
      state: present
    with_items:
      - "deb http://ppa.launchpad.net/videolan/stable-daily/ubuntu xenial main"
      - "deb-src http://ppa.launchpad.net/videolan/stable-daily/ubuntu xenial main"

  - name: install vlc
    apt: name=vlc update_cache=yes state=latest

  become: true
