---
- block:

  - name: add apt key
    apt_key:
      id: 68576280
      url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
      state: present

  - name: add ppa
    apt_repository: repo="{{ item }}" state=present filename=nodejs
    with_items:
      - "deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ distromap_distro_codename }} main"
      - "deb-src https://deb.nodesource.com/node_{{ nodejs_version }} {{ distromap_distro_codename }} main"

  - name: install node.js
    apt: "name=nodejs={{ nodejs_version | regex_replace('^(\\d+.)x', '\\1*') }} state=present force=yes update_cache=yes"

  become: true
