---
- block:

  - name: add apt signing key
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg state=present

  - name: add ppa
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ distromap_distro_codename }} stable"
      filename: docker

  - name: install docker
    apt: name=docker-ce state=latest update_cache=yes

  - name: add {{ ansible_env.LOGNAME }} to docker group
    user: name="{{ ansible_env.LOGNAME }}" groups=docker append=yes

  - name: start docker
    service: name=docker state=started enabled=yes

  become: true
