---
- block:

  - name: add apt signing key
    apt_key:
      id: F1656F24C74CD1D8
      keyserver: hkp://keyserver.ubuntu.com:80
      state: present

  - name: add ppa
    apt_repository:
      repo: "deb [arch=amd64,i386] http://nyc2.mirrors.digitalocean.com/mariadb/repo/10.3/{{ mariadb_distro_name }} {{ mariadb_distro_codename }} main"
      filename: mariadb103
      state: present

  - name: install mariadb server / client
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
      - mariadb-server-10.3
      - mariadb-client-10.3

  become: true
