---
- block:

  - name: add apt signing key
    apt_key:
      id: E1DD270288B4E6030699E45FA1715D88E1DF1F24
      keyserver: hkp://keyserver.ubuntu.com:80
      state: present
    register: git_apt_key_added
    ignore_errors: yes

  - name: add apt signing key
    apt_key:
      id: E1DD270288B4E6030699E45FA1715D88E1DF1F24
      keyserver: keyserver.ubuntu.com
      state: present
    when: git_apt_key_added is failed

  - name: add ppa
    apt_repository:
      repo: "{{ item }}"
      filename: git
      state: present
    with_items:
      - "deb http://ppa.launchpad.net/git-core/ppa/ubuntu {{ distromap_distro_codename }} main"
      - "deb-src http://ppa.launchpad.net/git-core/ppa/ubuntu {{ distromap_distro_codename }} main"

  - name: install git
    apt: name=git update_cache=yes state=latest

  become: true
