---
- block:

  - name: install apt utils
    apt: name="{{ item }}" state="present"
    with_items:
      - apt-transport-https
      - ca-certificates
      - gnupg2
      - software-properties-common

  become: true
