---
- block:

  - name: install docker-compose:{{ docker_compose_release }}
    get_url:
      url: https://github.com/docker/compose/releases/download/{{ docker_compose_release }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}
      dest: /usr/local/bin/docker-compose
      mode: 0755

  - name: install docker-compose:{{ docker_compose_release }} command completion
    get_url:
      url: https://raw.githubusercontent.com/docker/compose/{{ docker_compose_release }}/contrib/completion/bash/docker-compose
      dest: /etc/bash_completion.d/docker-compose
      mode: 0644

  become: true
